#!/usr/bin/env python3
"""
build_thesis.py — Assemble the Soma-Field research monograph in thesis format.

This is a companion to build_omnibus.py.  It uses the same paper bodies
but wraps them in thesis-specific apparatus:

  1. Thesis YAML frontmatter (title, subtitle, degree statement)
  2. Preamble chapter (Abstract, Declaration, Preface, Overview)
  3. All seventeen papers in five parts (same STRUCTURE as omnibus)
  4. Lean 4 Appendix (generated by build_lean_appendix.py)

Output
------
  paper/bld/thesis-body.md    (merged source)
  paper/bld/thesis-royal.pdf  (built by 'make thesis-royal')
  paper/bld/thesis-a4.pdf     (built by 'make thesis-a4')

Usage
-----
  make thesis          (builds both PDF variants)
  python scripts/build_thesis.py   (generates merged .md only)
"""

import re
import sys
from pathlib import Path

# Import shared helpers from build_omnibus — avoids duplicating STRUCTURE.
# Both scripts live in the same directory; Python resolves the import locally.
sys.path.insert(0, str(Path(__file__).parent))
from build_omnibus import STRUCTURE, get_body  # noqa: E402

# Also import the lean appendix generator so one call ensures it is up to date.
from build_lean_appendix import main as build_lean_appendix  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PAPER_DIR = REPO_ROOT / "paper"
BLD_DIR   = PAPER_DIR / "bld"

# ---------------------------------------------------------------------------
# Thesis frontmatter
# ---------------------------------------------------------------------------

FRONTMATTER = """\
---
title: "The Soma-Field and the Universal Somatic Field"
subtitle: "A Formal Theory of Affective Dynamics, Consciousness, and Scale-Invariant Geometry in Biological and Physical Systems"
author: "Alistair Johnson"
orcid: "0009-0007-2194-0850"
institute: "Independent Researcher, Zurich, Switzerland"
date: "2026"
lang: en-GB
description: "A research monograph presenting the Soma-Field Theory (SFT) and Universal Somatic Field (USF) framework across seventeen papers in five parts, with Lean 4 formal verification appendix. Covers: 8D BRECVEMA Hopfield model, M-theory compactification, quantum tunnelling in the limbic gate, FM-HN Correspondence Principle, swarm propagator, 20-scale Zoomable USF. All core theorems machine-verified."
bibliography: bibliography.bib
csl: apa-7th.csl
---"""

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    BLD_DIR.mkdir(exist_ok=True)

    # Ensure the lean appendix source is up to date.
    # (STRUCTURE already includes lean-proofs-appendix at the end.)
    print("Generating lean-proofs-appendix.md …")
    build_lean_appendix()

    out_path = BLD_DIR / "thesis-body.md"

    sections: list[str] = [FRONTMATTER]

    # Thesis preamble (abstract, declaration, preface, overview) — before Part I.
    preamble = get_body("thesis-preamble")
    if preamble:
        sections.append(f"\n\n{preamble}\n")
        print("  + thesis-preamble")

    # All seventeen papers + lean appendix (STRUCTURE is shared with omnibus).
    for part_divider, paper_name in STRUCTURE:
        if part_divider:
            sections.append(f"\n\n{part_divider}\n")
        if paper_name:
            body = get_body(paper_name)
            if body:
                sections.append(f"\n\n{body}\n")
                print(f"  + {paper_name}")

    output = "\n".join(sections)
    out_path.write_text(output, encoding="utf-8")

    lines    = output.count("\n")
    size_kb  = out_path.stat().st_size / 1024
    papers   = len(STRUCTURE) + 1  # +preamble

    print(f"\nWritten: {out_path.relative_to(REPO_ROOT)}")
    print(f"  Sections merged : {papers}")
    print(f"  Lines           : {lines:,}")
    print(f"  Size            : {size_kb:.0f} KB")
    print(f"\nRun 'make thesis' in paper/ to build the PDF.")


if __name__ == "__main__":
    main()
