-- Lulu 2026 A4 Dust Jacket geometry with the official Hardcover Linen spine table.
local function value(name)
  for index, argument in ipairs(arg) do
    if argument == name then return arg[index + 1] end
  end
  error("missing " .. name)
end
local cover, interior, title, subtitle, output = value("--cover"), value("--interior"), value("--title"), value("--subtitle"), value("--output")
local pipe = assert(io.popen('pdfinfo "' .. interior .. '"'))
local info = pipe:read("*a")
assert(pipe:close())
local pages = assert(tonumber(info:match("Pages:%s*(%d+)")), "could not read PDF page count")
local bands = {{24,84,6},{85,140,13},{141,168,16},{169,194,17},{195,222,19},{223,250,21},{251,278,22},{279,306,24},{307,334,25},{335,360,27},{361,388,29},{389,416,30},{417,444,32},{445,472,33},{473,500,35},{501,528,37},{529,556,38},{557,582,40},{583,610,41},{611,638,43},{639,666,44},{667,694,46},{695,722,48},{723,750,49},{751,778,51},{779,800,52}}
local spine
for _, band in ipairs(bands) do if pages >= band[1] and pages <= band[2] then spine = band[3] end end
assert(spine, string.format("%s has %d pages; Lulu Hardcover Linen Wrap allows 24-800", cover, pages))
local function tex(text) return text:gsub("([%%#$&_{}])", "\\%1") end
local flap, panel, bleed, height = 85.72, 216.25, 6.35, 316.09
-- Lulu's supplied A4 template declares 623.36 mm at its 6.35 mm minimum
-- spine. Preserve that measured canvas and vary only the official spine band.
local width = 623.36 - 6.35 + spine
local back = bleed + flap + panel / 2
local spine_center = bleed + flap + panel + spine / 2
local front = bleed + flap + panel + spine + panel / 2
local file = assert(io.open(output, "w"))
file:write(string.format("%% Generated by generate-config.lua\n\\def\\CoverCanvasWidth{%.2fmm}\n\\def\\CoverCanvasHeight{%.2fmm}\n\\def\\CoverBackCenterX{%.2fmm}\n\\def\\CoverSpineCenterX{%.2fmm}\n\\def\\CoverFrontCenterX{%.2fmm}\n\\def\\CoverPanelCenterY{%.2fmm}\n\\def\\CoverSpineTextWidth{%.2fmm}\n\\def\\CoverTitle{%s}\n\\def\\CoverSubtitle{%s}\n\\def\\CoverSpineText{%s}\n\\def\\CoverPageCount{%d}\n", width, height, back, spine_center, front, height / 2, math.max(spine - 6.35, 1), tex(title), tex(subtitle), tex(title), pages))
file:close()
print(string.format("%s: %d pages, %.0f mm spine, %.2f x %.2f mm dust jacket", cover, pages, spine, width, height))
